services:
  db:
    image: postgres
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./persist/dev-db:/var/lib/postgresql/data

  pgadminer:
    image: adminer
    ports:
      - "8080:8080"
    hostname: adminer
    container_name: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy

  api:
    build: ./server
    ports:
      - "3000:3000"
    restart: always
    command: npm run prod
    env_file: .env
    volumes:
      - ./server/src:/app/src/
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    command: npm run preview -- --host
    ports:
      - "4173:4173"
    env_file: .env
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./client/dist:/app/dist/
