services:
  db:
    image: postgres
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20

  pgadminer:
    image: adminer
    ports:
      - "8080:8080"
    hostname: adminer
    container_name: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy

  api:
    build: ./server
    ports:
      - "3000:3000"
    restart: always
    command: npm run prod
    env_file: .env
    volumes:
      - ./server/src:/app/src/
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    command: npm run dev
    ports:
      - "5173:5173"
    env_file: .env
    restart: always
    volumes:
      - ./client:/app
